FROM appliedis/alpine-gosu:3.3
MAINTAINER Jonathan Meyer <jon@gisjedi.com>

LABEL name="Lightweight Geospatial Data Abstraction Library (GDAL) on Alpine Linux" \
    vendor="Applied Information Sciences" \
    license="Apache v2.0"

RUN apk add --no-cache gdal --repository http://nl.alpinelinux.org/alpine/edge/testing
